masterpi/app/cars/views.py
"""
.. module:: carsView
   :synopsis: List of API for cars function

"""
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask_login import (
    current_user,
    login_required,
)

from app import db
from app.cars.models import Car, CarReport, CarLocation
from app.cars.maps import StaticMap
from flask_googlemaps import  Map, icons


mod = Blueprint('cars', __name__, url_prefix='/cars')


@mod.route('/details/<id>', methods=['GET'])
def details(id):
    """ 
    **Get detail information about the car**

    :param id: id of the car
    :type id: int

    :status 200: success
    :status 404: failed
    """
    car = Car.query.filter_by(id=id).first()
    if car.locations:
        gmap = StaticMap(car.current_location, id)
        carMap = gmap.create_map()
    else:
        carMap = None
    if car:
        return render_template("cars/details.html", car=car, carMap=carMap)
    return render_template("404.html")


@mod.route('/', methods=['GET'])
@login_required
def index():
    """
    **Get list of available car**

    This function allow user to get list of cars and its detail information

    :status 200: success
    :status 404: failed
    """
    cars = Car.query.all()
    return render_template("cars/index.html", cars=cars)
    




masterpi/app/users/views.py
import os, pickle, requests, json
import numpy as np
from json import JSONEncoder
import requests, json
import qrcode
import datetime
import jsonify

from json import JSONEncoder
from multiprocessing import Process
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app, abort
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import or_, and_, desc, func
from werkzeug.utils import secure_filename
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)
from flask_mail import Message

from app import db, login_manager, client, mail
from app.users.forms import RegisterForm, LoginForm, UserForm, UserEditForm, PhotosForm
from app.users.models import User
from app.cars.models import Car, CarReport, CarLocation
from app.cars.utils import get_current_location_coordinate, get_current_location_name
from app.cars.maps import StaticMap
from app.cars.forms import CarForm
from app.bookings.models import Booking, BookingAction
from ..facial_recognition.encode_faces import encode
from ..charting.prepare_chart_data import get_line_chart_data, get_pie_chart_data, get_bar_chart_data

mod = Blueprint('users', __name__, url_prefix='/')
api_mod = Blueprint('users_api', __name__, url_prefix='/api')
FACE_UPLOAD_FOLDER_URL = 'app/facial_recognition/dataset'
QR_UPLOAD_FOLDER_URL = 'app/qr_code'

class NumpyArrayEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NumpyArrayEncoder, self).default(obj)

def generate_qr_code(old_engineer_name, new_engineer_name):
    print(old_engineer_name)
    if old_engineer_name != '':
        oldfilename = old_engineer_name + '.png'
        dir = os.path.join(QR_UPLOAD_FOLDER_URL, oldfilename)
        if os.path.exists(dir):
            os.remove(dir)
    
    newfilename = new_engineer_name + '.png'
    directory = os.path.join(QR_UPLOAD_FOLDER_URL, newfilename)
    img = qrcode.make(new_engineer_name)
    img.save(directory)
    
@login_manager.user_loader
def load_user(user_id):
    """ retrieve the user on the database using user id 

    :param int id: the id of user
    
    :return: return user object with corresponding user id
    :rtype: User
    """
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    """ Redirect the user to login page if the user type is invalid
    """
    return redirect(url_for('users.login'))

@mod.route('/')
@login_required
def home():
    """ Redirect the user to home page which have booking history
    """
    bookings = Booking.query.filter_by(user_id=current_user.id) \
                            .order_by(Booking.id.desc()).all()
    return render_template("users/home.html", user=current_user, bookings=bookings)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """ This function login using register account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed, 
            # it's a safe place to store the user id
            login_user(user)
            return redirect(url_for('users.login_redirect'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@mod.route('/google-login/', methods=['GET'])
def google_login():
    """ Login form using Google account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    #ref: https://realpython.com/flask-google-login/
    #TODO: check if user's is logged in
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=url_for('users.google_callback', _external=True),
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)

@mod.route('/google-login/callback', methods=['GET'])
def google_callback():
    """ retrieve user information in Google account
    """
    #ref: https://realpython.com/flask-google-login/
    code = request.args.get("code")
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    token_endpoint = google_provider_cfg["token_endpoint"]
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(current_app.config['GOOGLE_CLIENT_ID'], 
              current_app.config['GOOGLE_CLIENT_SECRET']),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body).json()
    user = User.query.filter_by(email=userinfo_response['email']).first()
    if not user:
        user = User(userinfo_response['email'],
                    username=userinfo_response['sub'], 
                    first_name=userinfo_response['given_name'],
                    last_name=userinfo_response['family_name'])
        db.session.add(user)
        db.session.commit()
    login_user(user)
    return redirect(url_for('users.login_redirect'))

@mod.route('/login/redirect')
@login_required
def login_redirect():
    """ Redirect to page based on user role
    """
    if current_user.isEngineer():
        return redirect(url_for('users.engineer_reports'))
    if current_user.isManager():
        return redirect(url_for('users.dashboard'))
    if current_user.isAdmin():
        return redirect(url_for('users.admin_pages'))
    return redirect(url_for('users.home'))
 
@mod.route('/logout/')
@login_required
def logout():
    """ User logout 
    """
    logout_user()
    return redirect(url_for('users.login'))
  
@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """ Registration Form for register new account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # check whether if there is user with the same username/email
        user = User.query.filter(or_(User.username == form.username.data, 
                                     User.email == form.email.data)).first()
        if not user:
            # create an user instance not yet stored in the database
            user = User(form.email.data, 
                        username=form.username.data, 
                        first_name=form.first_name.data, 
                        last_name=form.last_name.data, 
                        password=generate_password_hash(form.password.data))
            # Insert the record in our database and commit it
            db.session.add(user)
            db.session.commit()

            # Log the user in, as he now has an id
            login_user(user)
            # redirect user to the 'home' method of the user module.
            return redirect(url_for('users.login_redirect'))
        flash('Username or email is taken.')
    return render_template("users/register.html", form=form)

@mod.route('/dashboard/')
@login_required
def dashboard():
    """ Redirect to dashboard
    """
    if not (current_user.isAdmin() or current_user.isManager()):
        abort(403)

    line_chart_data = get_line_chart_data()
    pie_chart_data = get_pie_chart_data()
    bar_chart_data = get_bar_chart_data()

    return render_template("users/dashboard.html", 
        line_chart_labels = line_chart_data['labels'],
        line_chart_values = line_chart_data['values'],
        pie_chart_labels = pie_chart_data['labels'],
        pie_chart_values = pie_chart_data['values'],
        bar_chart_labels = bar_chart_data['labels'],
        bar_chart_values = bar_chart_data['values']
    ) 
    
@mod.route('/engineer/')
@login_required
def engineer():
    """ Redirect to engineering page
    """
    return render_template("users/engineer.html")
  
@mod.route('/admin/bookings', methods=['GET'])
@login_required
def admin_bookings():
    """ Redirect the admin to booking page which show the list of bookings
    """
    if not current_user.isAdmin():
        abort(403)
    bookings = Booking.query.order_by(desc(Booking.id)).all()
    return render_template("users/admin/bookings.html", bookings=bookings)

@mod.route('/admin/cars', methods=['GET'])
@login_required
def admin_cars():
    """ Redirect the admin to car page which show the list of cars
    """
    if not current_user.isAdmin():
        abort(403)
    cars = Car.query.order_by(desc(Car.id)).all()
    return render_template("users/admin/cars.html", cars=cars)

@mod.route('/admin/cars/create', methods=['GET', 'POST'])
@login_required
def admin_cars_create():
    """ This function allow admin to create a car record in the database

        :reqheader Accept: application/json
        :param string make: car brand
        :param string color: car color
        :param string body_type: car body type
        :param int seats: number of seats

masterpi/app/templates/base.html
<!-- HEADER -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <title>{% block title %}Car Share IOT{% endblock %}</title>
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" media="screen">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" media="screen">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}" media="screen">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
    {% endblock %}
</head>
<body>
<!-- END_HEADER -->

{% if current_user.is_authenticated %}
<!-- NAVBAR -->
<div class="navbar navbar-expand-lg navbar-dark bg-primary">
	<div class="container"> <b class="navbar-brand">Car Share IOT</b>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item"><a class="nav-link" href="{{ url_for('users.home') }}">Home</a></li>
				{% if current_user.isAdmin() or current_user.isManager() %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('users.dashboard') }}">Dashboard</a></li>
				{% endif %}
				{% if current_user.isCustomer() %}
					<li class="nav-item"><a class="nav-link" href="{{ url_for('users.photos_upload') }}">Facial recognition</a></li>
				{% endif %}
				{% if current_user.isAdmin() %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin pages</a>
						<div class="dropdown-menu">
						<a class="dropdown-item" href="{{ url_for('users.admin_cars') }}">Cars</a>
						<a class="dropdown-item" href="{{ url_for('users.admin_users') }}">Users</a>
						<a class="dropdown-item" href="{{ url_for('users.admin_bookings') }}">Bookings</a>
						</div>
					</li>
				{% endif %}
				{% if current_user.isManager() %}
				<li class="nav-item"><a class="nav-link" href="{{ url_for('users.manager_reports') }}">Reported cars</a></li>
				{% endif %}
				<li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
			</ul>
			<div class="form-inline my-2 my-lg-0">
				{% if current_user.isCustomer() %}
					<a href="{{ url_for('cars.index') }}" class="btn btn-secondary my-2 my-sm-0" type="submit">
						<i class="fa fa-car" aria-hidden="true"></i> Book a car
					</a>
				{% elif current_user.isEngineer() %}
					<a href="{{ url_for('users.engineer_reports') }}" class="btn btn-secondary my-2 my-sm-0" type="submit">
						<i class="fa fa-file" aria-hidden="true"></i> View car reports
					</a>
				{% elif current_user.isManager() %}
					<a href="{{ url_for('users.dashboard') }}" class="btn btn-secondary my-2 my-sm-0" type="submit">
						<i class="fa fa-tachometer" aria-hidden="true"></i> Dashboard
					</a>
				{% elif current_user.isAdmin() %}
					<a href="{{ url_for('users.admin_pages') }}" class="btn btn-secondary my-2 my-sm-0" type="submit">
						<i class="fa fa-star" aria-hidden="true"></i> Admin pages
					</a>
				{% endif %}

			</div>
		</div>
	</div>
</div>
<!-- END_NAVBAR -->
{% endif %}

<div class="container main">
{% block content %}{% endblock %}

<footer id="footer">
    <div class="row">
      <div class="col-lg-12">
        <ul class="list-unstyled">
          <li class="float-lg-right"><a href="#top">Scroll to top <i class="fa fa-arrow-up" aria-hidden="true"></i></a></li>
          <li>Made with <i style="color:red" class="fa fa-heart"></i> by RMIT students.</li>
        </ul>
      </div>
    </div>
  </footer>
</div>

<!-- FOOTER -->
{% block script %}
<script src="{{ url_for('static', filename='js/jquery.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/custom.js') }}" type="text/javascript"></script>
{% endblock %}
</body>
</html>
<!-- END_FOOTer -->