masterpi/app/bookings/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app
from flask_login import current_user

from app import db
from app.bookings.models import Booking, BookingAction
from app.cars.models import Car, CarLocation, CarReport
from app.cars.utils import get_current_location_coordinate, get_current_location_name
from app.calendar_api.calendar_api import CalendarApi
from app.users.models import User

from datetime import datetime


mod = Blueprint('bookings', __name__, url_prefix = '/bookings')

@mod.route('/book', methods = ['POST'])
def book():
    """ This function allow user to book (POST) a car

        When user book a car, a booking record and booking action is created 

        :<json int car_id: id of a existing car
        :<json int duration: book duration (hours)

        :status 200: book created
    """
    car = Car.query.filter_by(id = request.form['car_id']).first()
    if car:
        user_id = current_user.id
    booking = Booking(user_id, car.id, request.form['duration'])
    db.session.add(booking)
    db.session.commit()
    bookingAction = BookingAction(booking.id, "created")
    db.session.add(bookingAction)
    db.session.commit()
    event = add_event_for_calendar(booking, bookingAction)
    booking.calendar_api = event['id']
    db.session.commit()
    return '', 200

@mod.route('/unlock', methods = ['POST'])
def unlock():
    """ This function allow user to unlock (POST) a car

        a booking action record for unlock is created

        :<json int booking_id: id of a booking record

        :status 200: car unlocked
    """
    bookingAction = BookingAction(request.form['booking_id'], "unlocked")
    db.session.add(bookingAction)
    db.session.commit()
    return '', 200

@mod.route('/cancel', methods = ['POST'])
def cancel():
    """ This function allow user to cancel (POST) a booking
        
        a booking action record for cancel booking is created

        :<json int booking_id: id of a booking record

        :status 200: book canceled
    """
    bookingAction = BookingAction(request.form['booking_id'], "cancelled")
    booking = Booking.query.filter_by(id = request.form['booking_id']).first()
    if booking.calendar_id:
        delete_event_calendar(booking.calendar_id)
    db.session.add(bookingAction)
    db.session.commit()
    return '', 200

@mod.route('/return', methods = ['POST'])
def return_():
    """ This function allow user to return (POST) a car

        a booking action record is created

        :<json int booking_id: id of a booking record

        :status 200: return succeed 
    """
    bookingAction = BookingAction(request.form['booking_id'], "returned")
    db.session.add(bookingAction)
    booking = Booking.query.get(request.form['booking_id'])
    current_location_coordinate = get_current_location_coordinate()
    current_location_name = get_current_location_name(**current_location_coordinate)
    carLocation = CarLocation(booking.car_id,
                              long=current_location_coordinate['lng'],
                              lat=current_location_coordinate['lat'],
                              location=current_location_name)
    db.session.add(carLocation)
    db.session.commit()
    return '', 200

def add_event_for_calendar(booking, bookingAction):
    """ This function will sent a calendar event to user who book the car 

    :param booking: booking of the car
    :param bookingAction: the booking action record of the car

    """
    user = User.query.filter_by(id = booking.user_id).first()
    title = "Book car {}".format(booking.car_id)
    description = "You have booked car {} at {} for {} hours. Your booking id is {}".format(booking.car_id, 
                                                                                            bookingAction.creation_time, 
                                                                                            booking.duration, 
                                                                                            booking.id)
    calendar = CalendarApi()
    event = calendar.add_event(title, description, user.email, bookingAction.creation_time, booking.duration)
    return event

def delete_event_calendar(event_id):
    """ this function delete event on the calendar

    :param str event_id: calender event id
    """
    calendar = CalendarApi()
    event = calendar.delete_event(event_id)

masterpi/app/cars/views.py
"""
.. module:: carsView
   :synopsis: List of API for cars function

"""
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask_login import (
    current_user,
    login_required,
)

from app import db
from app.cars.models import Car, CarReport, CarLocation
from app.cars.maps import StaticMap
from flask_googlemaps import  Map, icons


mod = Blueprint('cars', __name__, url_prefix='/cars')


@mod.route('/details/<id>', methods=['GET'])
def details(id):
    """ 
    **Get detail information about the car**

    :param id: id of the car
    :type id: int

    :status 200: success
    :status 404: failed
    """
    car = Car.query.filter_by(id=id).first()
    if car.locations:
        gmap = StaticMap(car.current_location, id)
        carMap = gmap.create_map()
    else:
        carMap = None
    if car:
        return render_template("cars/details.html", car=car, carMap=carMap)
    return render_template("404.html")


@mod.route('/', methods=['GET'])
@login_required
def index():
    """
    **Get list of available car**

    This function allow user to get list of cars and its detail information

    :status 200: success
    :status 404: failed
    """
    cars = Car.query.all()
    return render_template("cars/index.html", cars=cars)
    




masterpi/app/users/views.py
import os, pickle, requests, json
import numpy as np
from json import JSONEncoder
import requests, json
import qrcode
import datetime
import jsonify

from json import JSONEncoder
from multiprocessing import Process
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app, abort
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import or_, and_, desc, func
from werkzeug.utils import secure_filename
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)
from flask_mail import Message

from app import db, login_manager, client, mail
from app.users.forms import RegisterForm, LoginForm, UserForm, UserEditForm, PhotosForm
from app.users.models import User
from app.cars.models import Car, CarReport, CarLocation
from app.cars.utils import get_current_location_coordinate, get_current_location_name
from app.cars.maps import StaticMap
from app.cars.forms import CarForm
from app.bookings.models import Booking, BookingAction
from ..facial_recognition.encode_faces import encode
from ..charting.prepare_chart_data import get_line_chart_data, get_pie_chart_data, get_bar_chart_data

mod = Blueprint('users', __name__, url_prefix='/')
api_mod = Blueprint('users_api', __name__, url_prefix='/api')
FACE_UPLOAD_FOLDER_URL = 'app/facial_recognition/dataset'
QR_UPLOAD_FOLDER_URL = 'app/qr_code'

class NumpyArrayEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NumpyArrayEncoder, self).default(obj)

def generate_qr_code(old_engineer_name, new_engineer_name):
    print(old_engineer_name)
    if old_engineer_name != '':
        oldfilename = old_engineer_name + '.png'
        dir = os.path.join(QR_UPLOAD_FOLDER_URL, oldfilename)
        if os.path.exists(dir):
            os.remove(dir)
    
    newfilename = new_engineer_name + '.png'
    directory = os.path.join(QR_UPLOAD_FOLDER_URL, newfilename)
    img = qrcode.make(new_engineer_name)
    img.save(directory)
    
@login_manager.user_loader
def load_user(user_id):
    """ retrieve the user on the database using user id 

    :param int id: the id of user
    
    :return: return user object with corresponding user id
    :rtype: User
    """
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    """ Redirect the user to login page if the user type is invalid
    """
    return redirect(url_for('users.login'))

@mod.route('/')
@login_required
def home():
    """ Redirect the user to home page which have booking history
    """
    bookings = Booking.query.filter_by(user_id=current_user.id) \
                            .order_by(Booking.id.desc()).all()
    return render_template("users/home.html", user=current_user, bookings=bookings)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """ This function login using register account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed, 
            # it's a safe place to store the user id
            login_user(user)
            return redirect(url_for('users.login_redirect'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@mod.route('/google-login/', methods=['GET'])
def google_login():
    """ Login form using Google account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    #ref: https://realpython.com/flask-google-login/
    #TODO: check if user's is logged in
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=url_for('users.google_callback', _external=True),
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)

@mod.route('/google-login/callback', methods=['GET'])
def google_callback():
    """ retrieve user information in Google account
    """
    #ref: https://realpython.com/flask-google-login/
    code = request.args.get("code")
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    token_endpoint = google_provider_cfg["token_endpoint"]
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(current_app.config['GOOGLE_CLIENT_ID'], 
              current_app.config['GOOGLE_CLIENT_SECRET']),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body).json()
    user = User.query.filter_by(email=userinfo_response['email']).first()
    if not user:
        user = User(userinfo_response['email'],
                    username=userinfo_response['sub'], 
                    first_name=userinfo_response['given_name'],
                    last_name=userinfo_response['family_name'])
        db.session.add(user)
        db.session.commit()
    login_user(user)
    return redirect(url_for('users.login_redirect'))

@mod.route('/login/redirect')
@login_required
def login_redirect():
    """ Redirect to page based on user role
    """
    if current_user.isEngineer():
        return redirect(url_for('users.engineer_reports'))
    if current_user.isManager():
        return redirect(url_for('users.dashboard'))
    if current_user.isAdmin():
        return redirect(url_for('users.admin_pages'))
    return redirect(url_for('users.home'))
 
@mod.route('/logout/')
@login_required
def logout():
    """ User logout 
    """
    logout_user()
    return redirect(url_for('users.login'))
  
@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """ Registration Form for register new account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # check whether if there is user with the same username/email
        user = User.query.filter(or_(User.username == form.username.data, 
                                     User.email == form.email.data)).first()
        if not user:
            # create an user instance not yet stored in the database
            user = User(form.email.data, 
                        username=form.username.data, 
                        first_name=form.first_name.data, 
                        last_name=form.last_name.data, 
                        password=generate_password_hash(form.password.data))
            # Insert the record in our database and commit it
            db.session.add(user)
            db.session.commit()

            # Log the user in, as he now has an id
            login_user(user)
            # redirect user to the 'home' method of the user module.
            return redirect(url_for('users.login_redirect'))
        flash('Username or email is taken.')
    return render_template("users/register.html", form=form)

@mod.route('/dashboard/')
@login_required
def dashboard():
    """ Redirect to dashboard
    """
    if not (current_user.isAdmin() or current_user.isManager()):
        abort(403)

    line_chart_data = get_line_chart_data()
    pie_chart_data = get_pie_chart_data()
    bar_chart_data = get_bar_chart_data()

    return render_template("users/dashboard.html", 
        line_chart_labels = line_chart_data['labels'],
        line_chart_values = line_chart_data['values'],
        pie_chart_labels = pie_chart_data['labels'],
        pie_chart_values = pie_chart_data['values'],
        bar_chart_labels = bar_chart_data['labels'],
        bar_chart_values = bar_chart_data['values']
    ) 
    
@mod.route('/engineer/')
@login_required
def engineer():
    """ Redirect to engineering page
    """
    return render_template("users/engineer.html")
  
@mod.route('/admin/bookings', methods=['GET'])
@login_required
def admin_bookings():
    """ Redirect the admin to booking page which show the list of bookings
    """
    if not current_user.isAdmin():
        abort(403)
    bookings = Booking.query.order_by(desc(Booking.id)).all()
    return render_template("users/admin/bookings.html", bookings=bookings)

@mod.route('/admin/cars', methods=['GET'])
@login_required
def admin_cars():
    """ Redirect the admin to car page which show the list of cars
    """
    if not current_user.isAdmin():
        abort(403)
    cars = Car.query.order_by(desc(Car.id)).all()
    return render_template("users/admin/cars.html", cars=cars)

@mod.route('/admin/cars/create', methods=['GET', 'POST'])
@login_required
def admin_cars_create():
    """ This function allow admin to create a car record in the database

        :reqheader Accept: application/json
        :param string make: car brand
        :param string color: car color
        :param string body_type: car body type
        :param int seats: number of seats

masterpi/app/templates/users/dashboard.html
{% extends "base.html" %}
{% block content %}
<h1>Dashboard</h1>
<!--Line chart-->
<canvas id="line-chart" width="100" height="50"></canvas>
<script>
    var ctx = document.getElementById('line-chart').getContext('2d');
    var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'line',

    // The data for our dataset
    data: {
        labels: {{ line_chart_labels | tojson }},
        datasets: [{
            label: "Daily number of newly registered customers",
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            fill: false,
            lineTension:0,
            data: {{ line_chart_values }}
        }]
    },

    // Configuration options go here
    options: {
        scales: {
        yAxes: [{
            ticks: {
            beginAtZero: true,
            callback: function(value) {if (value % 1 === 0) {return value;}}
            }
        }]
        },
        title: {
            display: true, 
            fontSize: 20, 
            text: 'Number of daily new customers for the last 10 days'
        }
    }
});
</script>
<!--End Line chart-->
<br><br><br>

<!--Pie chart-->
<canvas id="pie-chart" width="100" height="50"></canvas>
<script>
    function getRandomColor() {
        var letters = '0123456789ABCDEF'.split('');
        var color = '#';
        for (var i = 0; i < 6; i++ ) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    values = {{ pie_chart_values }}
    colors = []
    for(let i=0; i<values.length; i++){
        colors.push('#' + Math.floor(Math.random()*16777215).toString(16));
    }   

    var options = {
        title: {
            display: true, 
            fontSize: 20,
            text: 'Percentage of cars make'
        },
        tooltips: {
            enabled: false
        },
        legend: {
            position: 'top',
        },
        plugins: {
            datalabels: {
                formatter: (value, ctx) => {
                    let sum = 0;
                    let dataArr = ctx.chart.data.datasets[0].data;
                    dataArr.map(data => {
                        sum += data;
                    });
                    let percentage = (value*100 / sum).toFixed(2)+"%";
                    return percentage;
                },
                color: '#fff',
            }
        }
    };
    
    var ctx = document.getElementById("pie-chart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            labels:{{ pie_chart_labels | tojson }},
            datasets: [{
                labels: {{ pie_chart_labels | tojson }},
                data: {{ pie_chart_values }},
                backgroundColor: colors,
                borderColor: "#fff"
            }]
        },
        options: options
    });

</script>
<!--End Pie chart-->

<br><br><br>
<!--Bar chart-->
<canvas id="bar-chart" width="100" height="50"></canvas>
<script>
    function getRandomColor() {
        var letters = '0123456789ABCDEF'.split('');
        var color = '#';
        for (var i = 0; i < 6; i++ ) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

    values = {{ bar_chart_values }}
    colors = []
    for(let i=0; i<values.length; i++){
        colors.push('#' + Math.floor(Math.random()*16777215).toString(16));
    }   

    new Chart(document.getElementById("bar-chart"), {
    type: 'bar',
    data: {
      labels: {{ bar_chart_labels | tojson }},
      datasets: [
        {
            backgroundColor: colors,
            data: {{ bar_chart_values }}
        }
      ]
    },
    options: {
        scales: {
        yAxes: [{
            ticks: {
            beginAtZero: true,
            callback: function(value) {if (value % 1 === 0) {return value;}}
            }
        }]
        },
      legend: { display: false },
      title: {
        display: true,
        fontSize: 20,
        text: "Number of car bookings with respect to cars' make in the last 10 days"
      }
    }
});
</script>
<!--End Bar chart-->
{% endblock %}

masterpi/app/templates/users/engineer.html
{% extends "base.html" %}
{% block content %}
<h1>Engineer</h1>
{% endblock %}

masterpi/app/templates/users/home.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1 class="display-3">Hello, {{ user.first_name if user.first_name else user.username }}!</h1>
    <p class="lead">It's nice to have you back with us. Have a nice day.</p>
    <hr class="my-4">
    <p class="lead">
      <a class="btn btn-secondary btn-lg shadow" href="{{ url_for('cars.index') }}" role="button">
        <i class="fa fa-car" aria-hidden="true"></i> Book a car
      </a>
    </p>
  </div>
  <div class="bs-docs-section">
    <div class="row">
      <div class="col-lg-12">
        <h1 class='page-header pb-3'>Your bookings:</h1>
      </div>
    </div>
    <div class="bs-component">

      <div class="row">
        
        {% for booking in bookings %}
        <div class="col-lg-4">
          <div class="card mb-3">
            <h4 class="card-header text-center"><a href={{ url_for('cars.details', id=booking.car_id) }}>{{ booking.car.make }}</a></h4>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">duration: <b>{{ booking.duration }} hour(s)</b></li>
              {% for action in booking.actions %}
                <li class="list-group-item">{{ action.action }} <b class="timeago" datetime="{{ action.creation_time }}"></b></li>
              {% endfor %}
            </ul>
            <div id="booking-footer-{{ booking.id }}" class="card-footer justify-content-between text-muted">
              {% if booking.booked %}
                <button onclick="cancelBooking({{ booking.id }})" class="btn btn-danger card-link">
                  <i class="fa fa-ban" aria-hidden="true"></i> Cancel
                </button>
              {% elif booking.unlocked %}
                  <button onclick="returnCar({{ booking.id }})" class="btn btn-success float-right card-link">
                    <i class="fa fa-reply" aria-hidden="true"></i> Return
                  </button>
              {% else %}
                Booking finished.
              {% endif %}
            </div>
          </div>
        </div>
        {% else %}
        <div class="col-lg-12">
          <p>your booking history is empty :(</p>
        </div>
        {% endfor %}        
      </div>  
    </div>
  </div>
{% endblock %}

{% block script %}
{{ super() }}
<!-- Book btn handler -->
<script src="{{ url_for('static', filename='js/timeago.min.js') }}" type="text/javascript"></script>
<script>
  timeago().render(document.querySelectorAll('.timeago'));

  function cancelBooking(booking_id) {
      $.ajax({
          url: '{{ url_for("bookings.cancel") }}',
          data: {
              booking_id: booking_id
          },
          type: 'POST',
          success: function (res) {
              $('#booking-footer-' + booking_id).html("Booking cancelled.");
          }
      })
  }

  function returnCar(booking_id) {
      $.ajax({
          url: '{{ url_for("bookings.return_") }}',
          data: {
              booking_id: booking_id
          },
          type: 'POST',
          success: function (res) {
              $('#booking-footer-' + booking_id).html("Car returned.");
          }
      })
  }

</script>
{% endblock %}

masterpi/app/templates/users/login.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid h-100 pt-5">
     <div class="row justify-content-center align-items-center h-100">
        <div class="col-lg-6 d-none d-lg-block">
           <div class="page-header">
              <h1 id="forms">Car Share IOT</h1>
              <img src="{{ url_for('static', filename='img/hero.svg') }}" class="img-fluid hero-img" alt="hero">
           </div>
        </div>
        <div class="col-lg-6 mx-auto login-form shadow">
           <div class="bs-component">
              <fieldset>
                 <legend><b>Login</b> / <a href="{{ url_for('users.register') }}">Register</a></legend>
                 <hr class="my-4">
                 <a href="{{ url_for('users.google_login') }}" type="button" class="btn btn-block btn-google shadow">
                 <i class="fa fa-google" aria-hidden="true"></i> Sign in with Google
                 </a>
                 <hr class="my-4">
                 {% from "forms/macros.html" import render_field, render_checkbox %}
                 <form method="POST" action="." class="form">
                    {{ form.csrf_token }}
                    <div class="form-group">
                      <p class="text-danger">{{ get_flashed_messages()[-1] }}</p>
                    </div>
                    {{ render_field(form.username, class="form-control") }}
                    {{ render_field(form.password, class="form-control") }}
                    {{ render_checkbox(form.remember_me, class="custom-control-input") }}
                    <button type="submit" class="btn btn-primary btn-block shadow">Login</button>
                 </form>
              </fieldset>
           </div>
        </div>
     </div>
</div>
{% endblock %}

masterpi/app/templates/users/photos-upload.html
{% extends "base.html" %}
{% block content %}
    {% if uploaded == False %}
        Please upload at least 3 portrait images for successful facial recognition.
        {% from "forms/macros.html" import render_field, render_checkbox %}
        <form method="POST" action="." enctype="multipart/form-data">
            {{ form.csrf_token }}
            {{ render_field(form.images, class="form-control") }}
            <button type="submit" class="btn btn-secondary">Upload</button>
        </form>
    {% else %}
        <p>Upload completed</p>
    {% endif %}
{% endblock %}

masterpi/app/templates/users/register.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid h-100 pt-5">
    <div class="row justify-content-center align-items-center h-100">
      <div class="col-lg-6 d-none d-lg-block">
          <div class="page-header">
          <h1 id="forms">Car Share IOT</h1>
          <img src="{{ url_for('static', filename='img/hero.svg') }}" class="img-fluid hero-img" alt="hero">
          </div>
      </div>
      <div class="col-lg-6 mx-auto register-form shadow">
          <div class="bs-component">
          <fieldset>
              <legend><a href="{{ url_for('users.login') }}">Login</a> / <b>Register</b></legend>
              <hr class="my-4">
              {% from "forms/macros.html" import render_field, render_checkbox %}
              <form method="POST" action="." class="form">
                  {{ form.csrf_token }}
                  <div class="form-group">
                    <p class="text-danger">{{ get_flashed_messages()[-1] }}</p>
                  </div>     
                  <div class="row">
                      <div class="col-lg-6">
                        {{ render_field(form.first_name, class="form-control") }}
                      </div>
                      <div class="col-lg-6">
                        {{ render_field(form.last_name, class="form-control") }}
                      </div>
                  </div>            
                  {{ render_field(form.username, class="form-control") }}
                  {{ render_field(form.email, class="form-control") }}
                  {{ render_field(form.password, class="form-control") }}
                  {{ render_checkbox(form.accept_tos, class="custom-control-input") }}
                  <button type="submit" class="btn btn-primary btn-block shadow">Register</button>
              </form>
          </fieldset>
      </div>
      </div>
  </div>
</div>

{% endblock %}