masterpi/app/cars/models.py
from app import db
from sqlalchemy.inspection import inspect
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship

class Car(db.Model):
    """ 
    Declare Car table and its attribute
    """
    __tablename__ = 'Car'
    id = db.Column(db.Integer, primary_key=True)
    make = db.Column(db.String(100))
    color = db.Column(db.String(100))
    body_type = db.Column(db.String(100))
    seats = db.Column(db.Integer)
    cost_per_hour = db.Column(db.Integer, nullable=False)
    available = db.Column(db.Boolean, nullable=False)
    reports = relationship("CarReport")
    bookings = relationship("Booking")
    locations = relationship("CarLocation")

    def __init__(self, make=None, color=None, body_type=None, 
                 seats=None, cost_per_hour=0):
        """ Constructor for Car model
        
        :param str make: brand of the car
        :param str color: color of the car
        :param str body_type: body type of car
        :param int seats: number of seat
        :param int cost_per_hour: cost per hour 
        """
        self.make = make
        self.color = color
        self.body_type = body_type
        self.seats = seats
        self.cost_per_hour = cost_per_hour

    def serialize_with_cols(self, cols):
        data = {c: getattr(self, c) for c in cols}
        return data

    @property
    def available(self):
        """ check car avalability
        """
        return not (self.booked or self.fixing)

    @property
    def booked(self):
        """ Check the booking status of car
        """
        return self.bookings and \
                (self.bookings[-1].booked or self.bookings[-1].unlocked)

    @property
    def fixing(self):
        """ check fixing status of car
        """
        return self.reports and not self.reports[-1].fixed

    @property
    def current_location(self):
        if not self.locations:
            return 'undefined'
        return self.locations[-1].location

    @property
    def current_coordinate(self):
        if not self.locations:
            return (0,0)
        return (self.locations[-1].lat, self.locations[-1].long) 

    def serialize(self):
        data = {c: getattr(self, c) for c in inspect(self).attrs.keys()}
        return data

    def __repr__(self):
        return '<Car %r>' % (self.id)

class CarLocation(db.Model):
    """
    Declare Carlocation table and its attributes
    """
    __tablename__ = 'CarLocation'
    id = db.Column(db.Integer, primary_key=True)
    car_id = db.Column(db.Integer, db.ForeignKey('Car.id'))
    location = db.Column(db.String(100))
    long = db.Column(db.Float())
    lat = db.Column(db.Float())
    creation_time = db.Column(db.DateTime(timezone=True), server_default=func.now())

    def __init__(self, car_id, location=None, long=None, lat=None):
        """ Constructor for the CarLocation
        
        :param int car_id: id of an existing car
        :param str location: location of an existing car
        """
        self.car_id = car_id
        self.location = location
        self.long = long
        self.lat = lat

    def __repr__(self):
        return '<CarLocation %r>' % (self.id)

class CarReport(db.Model):
    """ Declare CarReport table and its attribute"""
    __tablename__ = 'CarReport'
    id = db.Column(db.Integer, primary_key=True)
    car = relationship("Car")
    car_id = db.Column(db.Integer, db.ForeignKey('Car.id'))
    fixer = relationship("User")    
    fixer_id = db.Column(db.Integer, db.ForeignKey('User.id'))
    fixed = db.Column(db.Boolean, default=False)
    creation_time = db.Column(db.DateTime(timezone=True), server_default=func.now())
    update_time = db.Column(db.DateTime(timezone=True), onupdate=func.now())

    def __init__(self, car_id):
        """ constructor of CarReport
        """
        self.car_id = car_id

    def setFixer(self, fixer_id):
        """ Set fixer id 
        """
        self.fixer_id = fixer_id

    def setFixed(self, fixed=True):
        """ set fixed id
        """
        self.fixed = fixed

    def serialize(self):
        data = {c: getattr(self, c) for c in inspect(self).attrs.keys()}
        return data

    def __repr__(self):
        return '<CarReport %r>' % (self.id)

masterpi/app/cars/forms.py
from flask_wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField, IntegerField
from wtforms.validators import Required, EqualTo, Email

class searchForm(Form):
    keyWord = TextField('keyword', [Required()])

class CarForm(Form):
    make = TextField('Make')
    body_type = TextField('Body Type')
    color = TextField('Color')
    seats = IntegerField('Seats')
    cost_per_hour = IntegerField('Cost Per Hour')

masterpi/app/bookings/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app
from flask_login import current_user

from app import db
from app.bookings.models import Booking, BookingAction
from app.cars.models import Car, CarLocation, CarReport
from app.cars.utils import get_current_location_coordinate, get_current_location_name
from app.calendar_api.calendar_api import CalendarApi
from app.users.models import User

from datetime import datetime


mod = Blueprint('bookings', __name__, url_prefix = '/bookings')

@mod.route('/book', methods = ['POST'])
def book():
    """ This function allow user to book (POST) a car

        When user book a car, a booking record and booking action is created 

        :<json int car_id: id of a existing car
        :<json int duration: book duration (hours)

        :status 200: book created
    """
    car = Car.query.filter_by(id = request.form['car_id']).first()
    if car:
        user_id = current_user.id
    booking = Booking(user_id, car.id, request.form['duration'])
    db.session.add(booking)
    db.session.commit()
    bookingAction = BookingAction(booking.id, "created")
    db.session.add(bookingAction)
    db.session.commit()
    event = add_event_for_calendar(booking, bookingAction)
    booking.calendar_api = event['id']
    db.session.commit()
    return '', 200

@mod.route('/unlock', methods = ['POST'])
def unlock():
    """ This function allow user to unlock (POST) a car

        a booking action record for unlock is created

        :<json int booking_id: id of a booking record

        :status 200: car unlocked
    """
    bookingAction = BookingAction(request.form['booking_id'], "unlocked")
    db.session.add(bookingAction)
    db.session.commit()
    return '', 200

@mod.route('/cancel', methods = ['POST'])
def cancel():
    """ This function allow user to cancel (POST) a booking
        
        a booking action record for cancel booking is created

        :<json int booking_id: id of a booking record

        :status 200: book canceled
    """
    bookingAction = BookingAction(request.form['booking_id'], "cancelled")
    booking = Booking.query.filter_by(id = request.form['booking_id']).first()
    if booking.calendar_id:
        delete_event_calendar(booking.calendar_id)
    db.session.add(bookingAction)
    db.session.commit()
    return '', 200

@mod.route('/return', methods = ['POST'])
def return_():
    """ This function allow user to return (POST) a car

        a booking action record is created

        :<json int booking_id: id of a booking record

        :status 200: return succeed 
    """
    bookingAction = BookingAction(request.form['booking_id'], "returned")
    db.session.add(bookingAction)
    booking = Booking.query.get(request.form['booking_id'])
    current_location_coordinate = get_current_location_coordinate()
    current_location_name = get_current_location_name(**current_location_coordinate)
    carLocation = CarLocation(booking.car_id,
                              long=current_location_coordinate['lng'],
                              lat=current_location_coordinate['lat'],
                              location=current_location_name)
    db.session.add(carLocation)
    db.session.commit()
    return '', 200

def add_event_for_calendar(booking, bookingAction):
    """ This function will sent a calendar event to user who book the car 

    :param booking: booking of the car
    :param bookingAction: the booking action record of the car

    """
    user = User.query.filter_by(id = booking.user_id).first()
    title = "Book car {}".format(booking.car_id)
    description = "You have booked car {} at {} for {} hours. Your booking id is {}".format(booking.car_id, 
                                                                                            bookingAction.creation_time, 
                                                                                            booking.duration, 
                                                                                            booking.id)
    calendar = CalendarApi()
    event = calendar.add_event(title, description, user.email, bookingAction.creation_time, booking.duration)
    return event

def delete_event_calendar(event_id):
    """ this function delete event on the calendar

    :param str event_id: calender event id
    """
    calendar = CalendarApi()
    event = calendar.delete_event(event_id)

masterpi/app/cars/views.py
"""
.. module:: carsView
   :synopsis: List of API for cars function

"""
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask_login import (
    current_user,
    login_required,
)

from app import db
from app.cars.models import Car, CarReport, CarLocation
from app.cars.maps import StaticMap
from flask_googlemaps import  Map, icons


mod = Blueprint('cars', __name__, url_prefix='/cars')


@mod.route('/details/<id>', methods=['GET'])
def details(id):
    """ 
    **Get detail information about the car**

    :param id: id of the car
    :type id: int

    :status 200: success
    :status 404: failed
    """
    car = Car.query.filter_by(id=id).first()
    if car.locations:
        gmap = StaticMap(car.current_location, id)
        carMap = gmap.create_map()
    else:
        carMap = None
    if car:
        return render_template("cars/details.html", car=car, carMap=carMap)
    return render_template("404.html")


@mod.route('/', methods=['GET'])
@login_required
def index():
    """
    **Get list of available car**

    This function allow user to get list of cars and its detail information

    :status 200: success
    :status 404: failed
    """
    cars = Car.query.all()
    return render_template("cars/index.html", cars=cars)
    




masterpi/app/templates/cars/details.html
{% extends "base.html" %}
{% block content %}
<h1>Car details:</h1>
<div class="card-deck" id="cars-list">
        <div class="card" id="card{{ car.id }}">
            <div class="card-body">
                <h5 class="card-title">{{ car.make }}</h5>
                <table class="table card-body">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">details</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Id</th>
                            <td>{{ car.id }}</td>
                        </tr>
                        <tr>
                            <th scope="row">make</th>
                            <td>{{ car.make }}</td>
                        </tr>
                        <tr>
                            <th scope="row">color</th>
                            <td>{{ car.color }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Body Type</th>
                            <td>{{ car.body_type }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Seats</th>
                            <td>{{ car.seats }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Cost Per Hour</th>
                            <td>{{ car.cost_per_hour }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Current Location</th>
                            <td>{{ car.current_location }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div> 
            {% if carMap %}   
            {{ carMap.html }}
            {% else %}
            <h4>This car location is not recorded yet.</h4>
            {% endif %}
        </div>
</div>

{% endblock %}

{% block script %}
    {{ super() }}
    {{ carMap.js }}
{% endblock %}

masterpi/app/templates/cars/index.html
{% extends "base.html" %}
{% block content %}
<div class="form-group justify-content-between">
    <h1 class="d-inline">Available cars:</h1>
</div>

<div class="form-group">
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <span class="input-group-text">Search</span>
        </div>
        <input type="text" class="form-control" id="search-value"
            aria-label="Enter your search keywords here..."
            placeholder="Enter your search keywords here...">
    </div>
</div>

<div id="cars-list" class="row">
    {% for car in cars %}
        {% if car.available %}
            <div  id="card{{ car.id }}" class="col-lg-4 col-md-6 card-wrapper">
            <div class="bs-component">
                <div class="card mb-3 shadow">
                <h4 class="card-header text-center"><a href={{ url_for('cars.details', id=car.id) }}>{{ car.make }}</a></h4>
                <table class="table card-body mb-0">
                    <tbody>
                        <tr>
                            <th scope="row">Make</th>
                            <td>{{ car.make }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Color</th>
                            <td>{{ car.color }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Body Type</th>
                            <td>{{ car.body_type }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Seats</th>
                            <td>{{ car.seats }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Cost Per Hour</th>
                            <td>{{ car.cost_per_hour }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Location</th>
                            <td>{{ car.current_location }}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="card-footer">
                    <button href="#" onclick="booking_car({{ car.id }})"
                        class="btn btn-primary float-right" data-toggle="modal"
                        data-target="#booking-modal">Book this car</button>
                </div>
            </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
  </div>

<div id="booking-modal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"> Booking car </h4>
                <button type="button" class="close"
                    data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p>Car ID: <span id="booked-car"></span></p>
                <input type="text" class="form-control" id="duration"
                    aria-label="Enter number of hours you want to rent a car"
                    placeholder="Enter number of hours you want to rent a car">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary shadow" id="book-btn">Book</button>
            </div>
        </div>

    </div>
</div>

{% endblock %}

{% block script %}
{{ super() }}
<!-- search car function -->
<script>
    $(document).ready(function() {
        $('#search-value').keyup(function(){
            search_text($(this).val().toLowerCase());
        });
    
        function search_text(value){
            $('#cars-list .card-wrapper').each(function(){
                var found = 'false';
                $(this).each(function(){
                    if($(this).text().toLowerCase().indexOf(value.toLowerCase()) >= 0)
                    {
                        found = 'true';
                    }
                });
                if(found == 'true'){
                    $(this).fadeIn()
                }
                else {
                    $(this).fadeOut();
                }
            })
        }
    });
</script>

<!-- Book btn handler -->
<script>
    function booking_car(car_id) {
        $('#booked-car').text(car_id);
    }

    $("#book-btn").click(function () {
        car_id = $('#booked-car').text();
        duration = $('#duration').val();
        $.ajax({
            url: '{{ url_for("bookings.book") }}',
            data: {
                car_id: car_id,
                duration: duration,
            },
            type: 'POST',
            beforeSend: function() {
                $('#book-btn').text('Booking');
                $('#book-btn').prop('disabled', true);
                $('#duration').prop('disabled', true);
            },
            success: function (res) {
                $('#booking-modal').modal('hide');
                $('#card' + car_id).fadeOut();
                $('#card' + car_id).remove();
                $('#duration').val('');
            },
            complete: function() {
                $('#book-btn').text('Book');
                $('#duration').prop('disabled', false);
                $('#book-btn').prop('disabled', false);
            },        
        })
    });
</script>
{% endblock %}