masterpi/app/bookings/forms.py
from flask_wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField
from wtforms.validators import Required, EqualTo, Email

class durationForm(Form):
    duration = TextField('duration', [Required()])

masterpi/app/cars/forms.py
from flask_wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField, IntegerField
from wtforms.validators import Required, EqualTo, Email

class searchForm(Form):
    keyWord = TextField('keyword', [Required()])

class CarForm(Form):
    make = TextField('Make')
    body_type = TextField('Body Type')
    color = TextField('Color')
    seats = IntegerField('Seats')
    cost_per_hour = IntegerField('Cost Per Hour')

masterpi/app/bookings/views.py
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app
from flask_login import current_user

from app import db
from app.bookings.models import Booking, BookingAction
from app.cars.models import Car, CarLocation, CarReport
from app.cars.utils import get_current_location_coordinate, get_current_location_name
from app.calendar_api.calendar_api import CalendarApi
from app.users.models import User

from datetime import datetime


mod = Blueprint('bookings', __name__, url_prefix = '/bookings')

@mod.route('/book', methods = ['POST'])
def book():
    """ This function allow user to book (POST) a car

        When user book a car, a booking record and booking action is created 

        :<json int car_id: id of a existing car
        :<json int duration: book duration (hours)

        :status 200: book created
    """
    car = Car.query.filter_by(id = request.form['car_id']).first()
    if car:
        user_id = current_user.id
    booking = Booking(user_id, car.id, request.form['duration'])
    db.session.add(booking)
    db.session.commit()
    bookingAction = BookingAction(booking.id, "created")
    db.session.add(bookingAction)
    db.session.commit()
    event = add_event_for_calendar(booking, bookingAction)
    booking.calendar_api = event['id']
    db.session.commit()
    return '', 200

@mod.route('/unlock', methods = ['POST'])
def unlock():
    """ This function allow user to unlock (POST) a car

        a booking action record for unlock is created

        :<json int booking_id: id of a booking record

        :status 200: car unlocked
    """
    bookingAction = BookingAction(request.form['booking_id'], "unlocked")
    db.session.add(bookingAction)
    db.session.commit()
    return '', 200

@mod.route('/cancel', methods = ['POST'])
def cancel():
    """ This function allow user to cancel (POST) a booking
        
        a booking action record for cancel booking is created

        :<json int booking_id: id of a booking record

        :status 200: book canceled
    """
    bookingAction = BookingAction(request.form['booking_id'], "cancelled")
    booking = Booking.query.filter_by(id = request.form['booking_id']).first()
    if booking.calendar_id:
        delete_event_calendar(booking.calendar_id)
    db.session.add(bookingAction)
    db.session.commit()
    return '', 200

@mod.route('/return', methods = ['POST'])
def return_():
    """ This function allow user to return (POST) a car

        a booking action record is created

        :<json int booking_id: id of a booking record

        :status 200: return succeed 
    """
    bookingAction = BookingAction(request.form['booking_id'], "returned")
    db.session.add(bookingAction)
    booking = Booking.query.get(request.form['booking_id'])
    current_location_coordinate = get_current_location_coordinate()
    current_location_name = get_current_location_name(**current_location_coordinate)
    carLocation = CarLocation(booking.car_id,
                              long=current_location_coordinate['lng'],
                              lat=current_location_coordinate['lat'],
                              location=current_location_name)
    db.session.add(carLocation)
    db.session.commit()
    return '', 200

def add_event_for_calendar(booking, bookingAction):
    """ This function will sent a calendar event to user who book the car 

    :param booking: booking of the car
    :param bookingAction: the booking action record of the car

    """
    user = User.query.filter_by(id = booking.user_id).first()
    title = "Book car {}".format(booking.car_id)
    description = "You have booked car {} at {} for {} hours. Your booking id is {}".format(booking.car_id, 
                                                                                            bookingAction.creation_time, 
                                                                                            booking.duration, 
                                                                                            booking.id)
    calendar = CalendarApi()
    event = calendar.add_event(title, description, user.email, bookingAction.creation_time, booking.duration)
    return event

def delete_event_calendar(event_id):
    """ this function delete event on the calendar

    :param str event_id: calender event id
    """
    calendar = CalendarApi()
    event = calendar.delete_event(event_id)

masterpi/app/cars/views.py
"""
.. module:: carsView
   :synopsis: List of API for cars function

"""
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for
from flask_login import (
    current_user,
    login_required,
)

from app import db
from app.cars.models import Car, CarReport, CarLocation
from app.cars.maps import StaticMap
from flask_googlemaps import  Map, icons


mod = Blueprint('cars', __name__, url_prefix='/cars')


@mod.route('/details/<id>', methods=['GET'])
def details(id):
    """ 
    **Get detail information about the car**

    :param id: id of the car
    :type id: int

    :status 200: success
    :status 404: failed
    """
    car = Car.query.filter_by(id=id).first()
    if car.locations:
        gmap = StaticMap(car.current_location, id)
        carMap = gmap.create_map()
    else:
        carMap = None
    if car:
        return render_template("cars/details.html", car=car, carMap=carMap)
    return render_template("404.html")


@mod.route('/', methods=['GET'])
@login_required
def index():
    """
    **Get list of available car**

    This function allow user to get list of cars and its detail information

    :status 200: success
    :status 404: failed
    """
    cars = Car.query.all()
    return render_template("cars/index.html", cars=cars)
    




masterpi/app/users/views.py
import os, pickle, requests, json
import numpy as np
from json import JSONEncoder
import requests, json
import qrcode
import datetime
import jsonify

from json import JSONEncoder
from multiprocessing import Process
from flask import Blueprint, request, render_template, flash, g, session, redirect, url_for, current_app, abort
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy import or_, and_, desc, func
from werkzeug.utils import secure_filename
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user,
)
from flask_mail import Message

from app import db, login_manager, client, mail
from app.users.forms import RegisterForm, LoginForm, UserForm, UserEditForm, PhotosForm
from app.users.models import User
from app.cars.models import Car, CarReport, CarLocation
from app.cars.utils import get_current_location_coordinate, get_current_location_name
from app.cars.maps import StaticMap
from app.cars.forms import CarForm
from app.bookings.models import Booking, BookingAction
from ..facial_recognition.encode_faces import encode
from ..charting.prepare_chart_data import get_line_chart_data, get_pie_chart_data, get_bar_chart_data

mod = Blueprint('users', __name__, url_prefix='/')
api_mod = Blueprint('users_api', __name__, url_prefix='/api')
FACE_UPLOAD_FOLDER_URL = 'app/facial_recognition/dataset'
QR_UPLOAD_FOLDER_URL = 'app/qr_code'

class NumpyArrayEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.integer):
            return int(obj)
        elif isinstance(obj, np.floating):
            return float(obj)
        elif isinstance(obj, np.ndarray):
            return obj.tolist()
        else:
            return super(NumpyArrayEncoder, self).default(obj)

def generate_qr_code(old_engineer_name, new_engineer_name):
    print(old_engineer_name)
    if old_engineer_name != '':
        oldfilename = old_engineer_name + '.png'
        dir = os.path.join(QR_UPLOAD_FOLDER_URL, oldfilename)
        if os.path.exists(dir):
            os.remove(dir)
    
    newfilename = new_engineer_name + '.png'
    directory = os.path.join(QR_UPLOAD_FOLDER_URL, newfilename)
    img = qrcode.make(new_engineer_name)
    img.save(directory)
    
@login_manager.user_loader
def load_user(user_id):
    """ retrieve the user on the database using user id 

    :param int id: the id of user
    
    :return: return user object with corresponding user id
    :rtype: User
    """
    return User.query.get(user_id)

@login_manager.unauthorized_handler
def unauthorized():
    """ Redirect the user to login page if the user type is invalid
    """
    return redirect(url_for('users.login'))

@mod.route('/')
@login_required
def home():
    """ Redirect the user to home page which have booking history
    """
    bookings = Booking.query.filter_by(user_id=current_user.id) \
                            .order_by(Booking.id.desc()).all()
    return render_template("users/home.html", user=current_user, bookings=bookings)

@mod.route('/login/', methods=['GET', 'POST'])
def login():
    """ This function login using register account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))
    form = LoginForm(request.form)
    # make sure data are valid, but doesn't validate password is right
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed, 
            # it's a safe place to store the user id
            login_user(user)
            return redirect(url_for('users.login_redirect'))
        flash('Wrong username or password', 'error-message')
    return render_template("users/login.html", form=form)

@mod.route('/google-login/', methods=['GET'])
def google_login():
    """ Login form using Google account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    #ref: https://realpython.com/flask-google-login/
    #TODO: check if user's is logged in
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    authorization_endpoint = google_provider_cfg["authorization_endpoint"]
    request_uri = client.prepare_request_uri(
        authorization_endpoint,
        redirect_uri=url_for('users.google_callback', _external=True),
        scope=["openid", "email", "profile"],
    )
    return redirect(request_uri)

@mod.route('/google-login/callback', methods=['GET'])
def google_callback():
    """ retrieve user information in Google account
    """
    #ref: https://realpython.com/flask-google-login/
    code = request.args.get("code")
    google_provider_cfg = requests.get(current_app.config['GOOGLE_DISCOVERY_URL']).json()
    token_endpoint = google_provider_cfg["token_endpoint"]
    token_url, headers, body = client.prepare_token_request(
        token_endpoint,
        authorization_response=request.url,
        redirect_url=request.base_url,
        code=code
    )
    token_response = requests.post(
        token_url,
        headers=headers,
        data=body,
        auth=(current_app.config['GOOGLE_CLIENT_ID'], 
              current_app.config['GOOGLE_CLIENT_SECRET']),
    )

    # Parse the tokens!
    client.parse_request_body_response(json.dumps(token_response.json()))

    userinfo_endpoint = google_provider_cfg["userinfo_endpoint"]
    uri, headers, body = client.add_token(userinfo_endpoint)
    userinfo_response = requests.get(uri, headers=headers, data=body).json()
    user = User.query.filter_by(email=userinfo_response['email']).first()
    if not user:
        user = User(userinfo_response['email'],
                    username=userinfo_response['sub'], 
                    first_name=userinfo_response['given_name'],
                    last_name=userinfo_response['family_name'])
        db.session.add(user)
        db.session.commit()
    login_user(user)
    return redirect(url_for('users.login_redirect'))

@mod.route('/login/redirect')
@login_required
def login_redirect():
    """ Redirect to page based on user role
    """
    if current_user.isEngineer():
        return redirect(url_for('users.engineer_reports'))
    if current_user.isManager():
        return redirect(url_for('users.dashboard'))
    if current_user.isAdmin():
        return redirect(url_for('users.admin_pages'))
    return redirect(url_for('users.home'))
 
@mod.route('/logout/')
@login_required
def logout():
    """ User logout 
    """
    logout_user()
    return redirect(url_for('users.login'))
  
@mod.route('/register/', methods=['GET', 'POST'])
def register():
    """ Registration Form for register new account
    """
    if current_user.is_authenticated:
        return redirect(url_for('users.login_redirect'))    
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        # check whether if there is user with the same username/email
        user = User.query.filter(or_(User.username == form.username.data, 
                                     User.email == form.email.data)).first()
        if not user:
            # create an user instance not yet stored in the database
            user = User(form.email.data, 
                        username=form.username.data, 
                        first_name=form.first_name.data, 
                        last_name=form.last_name.data, 
                        password=generate_password_hash(form.password.data))
            # Insert the record in our database and commit it
            db.session.add(user)
            db.session.commit()

            # Log the user in, as he now has an id
            login_user(user)
            # redirect user to the 'home' method of the user module.
            return redirect(url_for('users.login_redirect'))
        flash('Username or email is taken.')
    return render_template("users/register.html", form=form)

@mod.route('/dashboard/')
@login_required
def dashboard():
    """ Redirect to dashboard
    """
    if not (current_user.isAdmin() or current_user.isManager()):
        abort(403)

    line_chart_data = get_line_chart_data()
    pie_chart_data = get_pie_chart_data()
    bar_chart_data = get_bar_chart_data()

    return render_template("users/dashboard.html", 
        line_chart_labels = line_chart_data['labels'],
        line_chart_values = line_chart_data['values'],
        pie_chart_labels = pie_chart_data['labels'],
        pie_chart_values = pie_chart_data['values'],
        bar_chart_labels = bar_chart_data['labels'],
        bar_chart_values = bar_chart_data['values']
    ) 
    
@mod.route('/engineer/')
@login_required
def engineer():
    """ Redirect to engineering page
    """
    return render_template("users/engineer.html")
  
@mod.route('/admin/bookings', methods=['GET'])
@login_required
def admin_bookings():
    """ Redirect the admin to booking page which show the list of bookings
    """
    if not current_user.isAdmin():
        abort(403)
    bookings = Booking.query.order_by(desc(Booking.id)).all()
    return render_template("users/admin/bookings.html", bookings=bookings)

@mod.route('/admin/cars', methods=['GET'])
@login_required
def admin_cars():
    """ Redirect the admin to car page which show the list of cars
    """
    if not current_user.isAdmin():
        abort(403)
    cars = Car.query.order_by(desc(Car.id)).all()
    return render_template("users/admin/cars.html", cars=cars)

@mod.route('/admin/cars/create', methods=['GET', 'POST'])
@login_required
def admin_cars_create():
    """ This function allow admin to create a car record in the database

        :reqheader Accept: application/json
        :param string make: car brand
        :param string color: car color
        :param string body_type: car body type
        :param int seats: number of seats

masterpi/app/templates/users/admin/bookings.html
{% extends "base.html" %}
{% block content %}
<div class="form-group justify-content-between">
  <h1 class="d-inline">Bookings</h1> 
</div>
<div class="form-group">
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Search:</span>
    </div>
    <input type="text" class="form-control" id="search-text" aria-label="Enter your query here..." placeholder="Enter your query here...">
  </div>
</div>
<table class="table table-hover" style="width:100%">
  <thead>
    <tr class="table-secondary">
      <th>ID</th>
      <th>Car</th>
      <th>Customer</th>
      <th>Duration</th>
      <th>Time</th>
    </tr>
  </thead>
  <tbody id="search-table">
    {% for booking in bookings %}
        <tr id="row{{ booking.id }}">
            <td>{{ booking.id }}</td>
            <td>{{ booking.car.make }}</td>
            <td>{{ booking.user.username }}</td>
            <td>{{ booking.duration }}</td>
            <td class="timeago" datetime="{{ booking.actions[0].creation_time }}"></td>
          </tr>
    {% endfor %}
  </tbody>
  </table>
{% endblock %}
{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/admin/table-search.js') }}" type="text/javascript"></script>
<script src="{{ url_for('static', filename='js/timeago.min.js') }}" type="text/javascript"></script>
<script>
  timeago().render(document.querySelectorAll('.timeago'));
</script>
{% endblock %}

masterpi/app/templates/users/admin/cars-create.html
{% extends "base.html" %}

{% block content %}

<div class="container">
     <div class="row">
        <div class="col-lg-12">
         <h1><a href="{{ url_for('users.admin_cars') }}">Cars</a><small class="lead"> / create</small></h1>
         <div class="form-group">
                <p class="text-info">{{ get_flashed_messages()[-1] }}</p>
              </div>     
           <div class="bs-component">
              <fieldset>
                 {% from "forms/macros.html" import render_field, render_checkbox %}
                 <form method="POST" action="" class="form">
                    {{ form.csrf_token }}
                    {{ render_field(form.make, class="form-control") }}
                    {{ render_field(form.body_type, class="form-control") }}
                    {{ render_field(form.color, class="form-control") }}
                    {{ render_field(form.seats, class="form-control") }}
                    {{ render_field(form.cost_per_hour, class="form-control") }}
                    <button type="submit" class="btn btn-primary btn-block">Create</button>
                 </form>
              </fieldset>
           </div>
        </div>
     </div>
</div>
{% endblock %}

masterpi/app/templates/users/admin/cars-edit.html
{% extends "base.html" %}

{% block content %}

<div class="container">
     <div class="row">
        <div class="col-lg-12">
            <h1><a href="{{ url_for('users.admin_cars') }}">Cars</a><small class="lead"> / edit</small></h1>
            <div class="form-group">
                <p class="text-info">{{ get_flashed_messages()[-1] }}</p>
              </div>     
           <div class="bs-component">
              <fieldset>
                 {% from "forms/macros.html" import render_field, render_checkbox %}
                 <form method="POST" action="" class="form">
                    {{ form.csrf_token }}
                    {{ render_field(form.make, class="form-control") }}
                    {{ render_field(form.body_type, class="form-control") }}
                    {{ render_field(form.color, class="form-control") }}
                    {{ render_field(form.seats, class="form-control") }}
                    {{ render_field(form.cost_per_hour, class="form-control") }}
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                 </form>
              </fieldset>
           </div>
        </div>
     </div>
</div>
{% endblock %}

masterpi/app/templates/users/admin/cars.html
{% extends "base.html" %}
{% block content %}
<div class="form-group justify-content-between">
  <h1 class="d-inline">Cars</h1> 
  <a href="{{ url_for('users.admin_cars_create') }}" target="_blank" type="button" class="btn btn-secondary float-right">Add new car</a>
</div>
<div class="form-group">
  <div class="input-group mb-3">
    <div class="input-group-prepend">
      <span class="input-group-text">Search:</span>
    </div>
    <input type="text" class="form-control" id="search-text" aria-label="Enter your query here..." placeholder="Enter your query here...">
  </div>
</div>
<table class="table table-hover" style="width:100%">
  <thead>
    <tr class="table-secondary">
      <th>ID</th>
      <th>Make</th>
      <th>Color</th>
      <th>Body Type</th>
      <th>Seats</th>
      <th>Cost Per Hour</th>
      <th>Available</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody id="search-table">
    {% for car in cars %}
        <tr id="row{{ car.id }}">
            <td>{{ car.id }}</td>
            <td>{{ car.make }}</td>
            <td>{{ car.color }}</td>
            <td>{{ car.body_type }}</td>
            <td>{{ car.seats }}</td>
            <td>{{ car.cost_per_hour }}</td>
            <td id="available-status{{ car.id }}">{{ "yes" if car.available else "no" }}</td>
            <td>
              <a href="{{ url_for('users.admin_cars_edit', car_id=car.id) }}" target="_blank" class="btn btn-sm btn-info" title="Edit">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              </a>
              <button onclick='delete_car({{ car.id }})' type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal" title="Delete">
                <i class="fa fa-trash" aria-hidden="true"></i>
              </button>
              {% if not (car.fixing or car.booked) %}
              <button id="report-btn{{ car.id }}" onclick='report_car({{ car.id }})' type="button" class="btn btn-sm btn-warning" data-toggle="modal" data-target="#report-modal"  title="Report">
                <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
              </button>
              {% endif %}
            </td>
          </tr>
    {% endfor %}
  </tbody>
  </table>


  <div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete car with ID: <strong id="delete-item">10</strong>?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" id="delete-btn">Delete</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="report-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to report car with ID: <strong id="report-item">10</strong>?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-link" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-warning" id="report-btn">Report</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}
{% block script %}
{{ super() }}
<script src="{{ url_for('static', filename='js/admin/table-search.js') }}" type="text/javascript"></script>
<script>
  function delete_car(car_id) {
    $('#delete-item').text(car_id);
  }

  function report_car(car_id) {
    $('#report-item').text(car_id);
  }

  $(document).ready(function(){
      $("#delete-btn").click(function(){    
          car_id = $('#delete-item').text();
          $.ajax({
              url: '{{ url_for("users.admin_cars_delete") }}',
              data: {
                  car_id: car_id,
              },
              type: 'POST',
              beforeSend: function() {
                $('#row' + car_id).addClass('table-danger');
              },
              success: function(res) {
                  $('#delete-modal').modal('hide');
                  $('#row' + car_id).fadeOut();
                  $('#row' + car_id).remove();
              },
              error: function(error) {
                  $('#delete-modal').modal('hide');
                  $('#row' + car_id).removeClass('table-danger');
              }
          })
      });
      $("#report-btn").click(function(){    
          car_id = $('#report-item').text();
          $.ajax({
              url: '{{ url_for("users.admin_cars_report") }}',
              data: {
                  car_id: car_id,
              },
              type: 'POST',
              success: function(res) {
                  $('#report-modal').modal('hide');
                  $('#report-btn' + car_id).fadeOut();
                  $('#available-status' + car_id).text("no");
              },
              error: function(error) {
                  $('#report-modal').modal('hide');
              }
          })
      });
  });
  </script>
{% endblock %}

masterpi/app/templates/users/admin/pages.html
{% extends "base.html" %}
{% block content %}
<h2>Admin Pages:</h2>
<div class="row">
    <div class="col-lg-4">
            <a href="{{ url_for('users.admin_users') }}">
                <h3 class="card-header text-center shadow">
                    <i class="fa fa-user" aria-hidden="true"></i> Users
                </h3>
            </a>
    </div>
    <div class="col-lg-4">
            <a href="{{ url_for('users.admin_cars') }}">
                <h3 class="card-header text-center shadow">
                    <i class="fa fa-car" aria-hidden="true"></i> Cars
                </h3>
            </a>
    </div>
    <div class="col-lg-4">
            <a href="{{ url_for('users.admin_bookings') }}">
                <h3 class="card-header text-center shadow">
                    <i class="fa fa-bookmark" aria-hidden="true"></i> Bookings
                </h3>
            </a>
    </div>
</div>
{% endblock %}

masterpi/app/templates/users/admin/users-create.html
{% extends "base.html" %}

{% block content %}

<div class="container">
     <div class="row">
        <div class="col-lg-12">
         <h1><a href="{{ url_for('users.admin_users') }}">Users</a><small class="lead"> / create</small></h1>
         <div class="form-group">
                <p class="text-info">{{ get_flashed_messages()[-1] }}</p>
              </div>     
           <div class="bs-component">
              <fieldset>
                 {% from "forms/macros.html" import render_field, render_select %}
                 <form method="POST" action="" class="form">
                    {{ form.csrf_token }}
                    {{ render_field(form.username, class="form-control") }}
                    {{ render_field(form.password, class="form-control") }}
                    {{ render_field(form.email, class="form-control") }}
                    {{ render_field(form.first_name, class="form-control") }}
                    {{ render_field(form.last_name, class="form-control") }}
                    {{ render_select(form.role, id="role") }}
                    {{ render_field(form.bluetooth_MAC, class="form-control", id="bluetooth_MAC") }}
                    <button type="submit" class="btn btn-primary btn-block">Create</button>
                 </form>
              </fieldset>
           </div>
        </div>
     </div>
</div>

{% endblock %}

{% block script %}
{{ super() }}
<script type="text/javascript">
   $("#bluetooth_MAC").prop( "disabled", true );
   $(document).ready(function(){
   $("select#role").change(function(){
      var selectedRole = $(this).children("option:selected").val();
      switch(selectedRole){
         case '2':
            $("#bluetooth_MAC").prop( "disabled", false );
            break;
         default:
            $("#bluetooth_MAC").prop( "disabled", true );
            break;
      }
   });
});
</script>
{% endblock %}

masterpi/app/templates/users/admin/users-edit.html
{% extends "base.html" %}

{% block content %}

<div class="container">
     <div class="row">
        <div class="col-lg-12">
            <h1><a href="{{ url_for('users.admin_users') }}">Users</a><small class="lead"> / edit</small></h1>
            <div class="form-group">
                <p class="text-info">{{ get_flashed_messages()[-1] }}</p>
              </div>     
           <div class="bs-component">
              <fieldset>
                 {% from "forms/macros.html" import render_field, render_select %}
                 <form method="POST" action="" class="form">
                    {{ form.csrf_token }}
                    {{ render_field(form.username, class="form-control") }}
                    {{ render_field(form.email, class="form-control") }}
                    {{ render_field(form.first_name, class="form-control") }}
                    {{ render_field(form.last_name, class="form-control") }}
                    {{ render_select(form.role) }}
                    {{ render_field(form.bluetooth_MAC, class="form-control", id="bluetooth_MAC") }}
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                 </form>
              </fieldset>
           </div>
        </div>
     </div>
</div>
{% endblock %}

{% block script %}
{{ super() }}
<script type="text/javascript">
   $("#bluetooth_MAC").prop( "disabled", true );
   $(document).ready(function(){
   $("select#role").change(function(){
      var selectedRole = $(this).children("option:selected").val();
      switch(selectedRole){
         case '2':
            $("#bluetooth_MAC").prop( "disabled", false );
            break;
         default:
            $("#bluetooth_MAC").prop( "disabled", true );
            break;
      }
   });
});
</script>
{% endblock %}